In [ ]:
import pandas as pd
import numpy as np

def input_matrix(matrix_number):
    print(f"\nEnter details for Matrix {matrix_number}:")
    rows = int(input("Enter number of rows: "))
    cols = int(input("Enter number of columns: "))

    matrix = []
    print("Enter the matrix elements row-wise (space-separated):")
    for i in range(rows):
        row = list(map(float, input(f"Row {i+1}: ").split()))
        if len(row) != cols:
            print("Error: Number of elements doesn't match the column count.")
            return None
        matrix.append(row)

    return np.array(matrix)

def add_matrices(A, B):
    if A.shape != B.shape:
        print("Error: Matrices must be of the same size for addition.")
        return None
    return A + B

def subtract_matrices(A, B):
    if A.shape != B.shape:
        print("Error: Matrices must be of the same size for subtraction.")
        return None
    return A - B

def multiply_matrices(A, B):
    if A.shape[1] != B.shape[0]:
        print("Error: Columns of Matrix A must match rows of Matrix B for multiplication.")
        return None
    return np.dot(A, B)

def transpose_matrix(A):
    return A.T

def determinant_matrix(A):
    if A.shape[0] != A.shape[1]:
        print("Error: Determinant can only be calculated for square matrices.")
        return None
    return np.linalg.det(A)

def display_menu():
    print("\n========== Matrix Operations Tool ==========")
    print("1. Add Matrices")
    print("2. Subtract Matrices")
    print("3. Multiply Matrices")
    print("4. Transpose a Matrix")
    print("5. Determinant of a Matrix")
    print("6. Exit")
    print("============================================")

def main():
    while True:
        display_menu()
        choice = input("Choose an operation (1–6): ")

        if choice == '1':
            A = input_matrix(1)
            B = input_matrix(2)
            if A is not None and B is not None:
                result = add_matrices(A, B)
                if result is not None:
                    print("\nResult of Matrix Addition:\n", result)

        elif choice == '2':
            A = input_matrix(1)
            B = input_matrix(2)
            if A is not None and B is not None:
                result = subtract_matrices(A, B)
                if result is not None:
                    print("\nResult of Matrix Subtraction:\n", result)

        elif choice == '3':
            A = input_matrix(1)
            B = input_matrix(2)
            if A is not None and B is not None:
                result = multiply_matrices(A, B)
                if result is not None:
                    print("\nResult of Matrix Multiplication:\n", result)

        elif choice == '4':
            A = input_matrix(1)
            if A is not None:
                result = transpose_matrix(A)
                print("\nTranspose of the Matrix:\n", result)

        elif choice == '5':
            A = input_matrix(1)
            if A is not None:
                result = determinant_matrix(A)
                if result is not None:
                    print(f"\nDeterminant of the Matrix: {round(result, 2)}")

        elif choice == '6':
            print("\nExiting the program. Thank you for using Matrix Operations Tool!")
            break

        else:
            print("Invalid choice. Please enter a number between 1 and 6.")

# Run the program
if __name__ == "__main__":
    main()


========== Matrix Operations Tool ==========
1. Add Matrices
2. Subtract Matrices
3. Multiply Matrices
4. Transpose a Matrix
5. Determinant of a Matrix
6. Exit


Choose an operation (1–6):  1



Enter details for Matrix 1:


Enter number of rows:  3
Enter number of columns:  3


Enter the matrix elements row-wise (space-separated):


Row 1:  1 4 7
Row 2:  2 5 8
Row 3:  3 6 9



Enter details for Matrix 2:


Enter number of rows:  3
Enter number of columns:  3


Enter the matrix elements row-wise (space-separated):


Row 1:  1 2 3
Row 2:  4 5 6
Row 3:  7 8 9



Result of Matrix Addition:
 [[ 2.  6. 10.]
 [ 6. 10. 14.]
 [10. 14. 18.]]

========== Matrix Operations Tool ==========
1. Add Matrices
2. Subtract Matrices
3. Multiply Matrices
4. Transpose a Matrix
5. Determinant of a Matrix
6. Exit
